// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	ID        uint32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt uint32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt uint32  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *uint32 `gorm:"column:deleted_at" json:"deleted_at"`
	CodeName  string  `gorm:"column:code_name;not null" json:"code_name"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
