// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID        uint32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Label     string  `gorm:"column:label;not null" json:"label"`
	CreatedAt uint32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt uint32  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *uint32 `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
