// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStaff = "staffs"

// Staff mapped from table <staffs>
type Staff struct {
	ID        uint32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt uint32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt uint32  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt *uint32 `gorm:"column:deleted_at" json:"deleted_at"`
	RolesID   uint32  `gorm:"column:roles_id;not null" json:"roles_id"`
	Username  string  `gorm:"column:username;not null" json:"username"`
	Password  string  `gorm:"column:password;not null" json:"password"`
	Fullname  *string `gorm:"column:fullname" json:"fullname"`
	IsActive  bool    `gorm:"column:is_active;not null;default:1" json:"is_active"`
	IsAdmin   bool    `gorm:"column:is_admin;not null" json:"is_admin"`
	LastLogin *uint32 `gorm:"column:last_login" json:"last_login"`
	LastIP    *string `gorm:"column:last_ip" json:"last_ip"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
