export const ConfigName = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
};

export const Permissions = {
  ROLES_CREATE: 'ROLES_CREATE',
  ROLES_READ: 'ROLES_READ',
  ROLES_UPDATE: 'ROLES_UPDATE',
  ROLES_DELETE: 'ROLES_DELETE',
  STAFFS_CREATE: 'STAFFS_CREATE',
  STAFFS_READ: 'STAFFS_READ',
  STAFFS_UPDATE: 'STAFFS_UPDATE',
  STAFFS_DELETE: 'STAFFS_DELETE',
};
